// <auto-generated />
using System;
using Banking_App_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace banking_app_api.Migrations
{
    [DbContext(typeof(BankAppDbContext))]
    [Migration("20260512111211_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Banking_App_API.Models.Account", b =>
                {
                    b.Property<string>("AccNo")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("AccNo");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("Banking_App_API.Models.AccountHolder", b =>
                {
                    b.Property<string>("ClientId")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("AccNo")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CardNo")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("LastAccessDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastDepositDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastWithdrawalDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ClientId", "AccNo", "CardNo");

                    b.HasIndex("AccNo");

                    b.HasIndex("CardNo");

                    b.ToTable("AccountHolder");
                });

            modelBuilder.Entity("Banking_App_API.Models.Card", b =>
                {
                    b.Property<string>("CardNo")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("CVV")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IssuingBank")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NetworkProvider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Pin")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("CardNo");

                    b.ToTable("Card");
                });

            modelBuilder.Entity("Banking_App_API.Models.Client", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MobileAppPassword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Banking_App_API.Models.ClientAddress", b =>
                {
                    b.Property<string>("ClientId")
                        .HasColumnType("varchar(20)");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.HasKey("ClientId", "AddressId");

                    b.HasIndex("AddressId");

                    b.ToTable("ClientAddress");
                });

            modelBuilder.Entity("Banking_App_API.Models.PhysicalAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("PostalCode")
                        .HasColumnType("int");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("StreetNo")
                        .HasColumnType("int");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("PhysicalAddress");
                });

            modelBuilder.Entity("Banking_App_API.Models.AccountHolder", b =>
                {
                    b.HasOne("Banking_App_API.Models.Account", "Account")
                        .WithMany("ClientsAndCards")
                        .HasForeignKey("AccNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Banking_App_API.Models.Card", "Card")
                        .WithMany("ClientsAndAccounts")
                        .HasForeignKey("CardNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Banking_App_API.Models.Client", "Client")
                        .WithMany("AccountsAndCards")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Card");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Banking_App_API.Models.ClientAddress", b =>
                {
                    b.HasOne("Banking_App_API.Models.PhysicalAddress", "PhysicalAddress")
                        .WithMany("ClientAddresses")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Banking_App_API.Models.Client", "Client")
                        .WithMany("PhysicalAddresses")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("PhysicalAddress");
                });

            modelBuilder.Entity("Banking_App_API.Models.Account", b =>
                {
                    b.Navigation("ClientsAndCards");
                });

            modelBuilder.Entity("Banking_App_API.Models.Card", b =>
                {
                    b.Navigation("ClientsAndAccounts");
                });

            modelBuilder.Entity("Banking_App_API.Models.Client", b =>
                {
                    b.Navigation("AccountsAndCards");

                    b.Navigation("PhysicalAddresses");
                });

            modelBuilder.Entity("Banking_App_API.Models.PhysicalAddress", b =>
                {
                    b.Navigation("ClientAddresses");
                });
#pragma warning restore 612, 618
        }
    }
}
